# self_correction/__init__.py

"""
RESDSQL Self-Correction Module

A module for correcting SQL queries generated by RESDSQL using LLM-based post-processing,
inspired by DIN-SQL's self-correction approach.
"""

from .config import SelfCorrectionConfig
from .self_correction_module import SelfCorrectionModule
from .prompt_generator import PromptGenerator, PromptStrategy
from .llm_api import QwenAPIClient, LLMError
from .sql_validator import SQLValidator, ExecutionResult

__version__ = "1.0.0"
__author__ = "RESDSQL Self-Correction Team"

__all__ = [
    "SelfCorrectionConfig",
    "SelfCorrectionModule", 
    "PromptGenerator",
    "PromptStrategy",
    "QwenAPIClient",
    "LLMError",
    "SQLValidator",
    "ExecutionResult"
]